# Written by Yanda Huang <yanda@cmu.edu>
# based on https://github.com/IoLanguage/io/blob/master/modules/FindODE.cmake
# Find Draw Stuff

FIND_PATH(DRAWSTUFF_INCLUDE_DIR drawstuff/drawstuff.h
    /usr/local/include/
)

SET(DRAW_NAMES ${DRAW_NAMES} drawstuff libdrawstuff)
FIND_LIBRARY(DRAWSTUFF_LIBRARY NAMES ${DRAW_NAMES} PATH)

IF(DRAWSTUFF_LIBRARY)
    MESSAGE(STATUS "Found DrawStuff library: ${DRAWSTUFF_LIBRARY}")
ELSE(DRAWSTUFF_LIBRARY)
    MESSAGE(STATUS "Couldn't find DrawStuff library: ${DRAWSTUFF_LIBRARY}")
ENDIF(DRAWSTUFF_LIBRARY)

IF(DRAWSTUFF_INCLUDE_DIR AND DRAWSTUFF_LIBRARY)
	SET(DRAWSTUFF_FOUND TRUE CACHE STRING "Whether DrawStuff was found or not")
ENDIF(DRAWSTUFF_INCLUDE_DIR AND DRAWSTUFF_LIBRARY)

IF(DRAWSTUFF_FOUND)
	IF(NOT DRAWSTUFF_FOUND_FIND_QUIETLY)
		MESSAGE(STATUS "Found DrawStuff: ${DRAWSTUFF_LIBRARY}")
	ENDIF (NOT DRAWSTUFF_FOUND_FIND_QUIETLY)
ELSE(DRAWSTUFF_FOUND)
	IF(DRAWSTUFF_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find DrawStuff")
	ENDIF(DRAWSTUFF_FIND_REQUIRED)
ENDIF(DRAWSTUFF_FOUND)
